apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: {{ .Values.consoleService.name }}
      port: {{ .Values.consoleService.port }}
      targetPort: {{ .Values.consoleService.name }}
      nodePort: {{ .Values.consoleService.nodePort }}
      protocol: TCP
    - name: {{ .Values.apiService.name }}
      port: {{ .Values.apiService.port }}
      targetPort: {{ .Values.apiService.name }}
      nodePort: {{ .Values.apiService.nodePort }}
      protocol: TCP
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
